### ISSUE TITLE
Study Guide

### ISSUE THREAD

**Issue by Aleksq7-M** [learn-co-curriculum/phase-2-quiz-components-and-props#1]
The instructions say I'm to create a study guide from the questions I got wrong, but after completing my first attempt, I'm told that I don't get to see my wrong answers until completing all attempts, which I think defeats the purpose of multiple attempts in the first place. Why try making a study guide if I don't know what I got wrong? This resulted in me just doing three blind attempts of the quiz, with my score barely changing.

**Comment by ihollander** [comment]
Hi @Aleksq7-M, thanks for your feedback! We're working on putting together some more guidance for students on how to get the most out of quizzes, so you should see more information on that later on in the program. What I'd suggest when putting together a study guide is:

- Look at which questions are marked as incorrect (like in the screenshot below). You should be able to see the **incorrect** answers after your first attempt, even though the correct answers won't be labeled until after you've taken the maximum number of attempts.
- Read the comments next to your answer(s) for more context
- Look at the Source/s at the bottom of the question: this will provide links to the pages in Canvas where the concepts in this question were discussed
- Review those sources before re-taking the quiz

![question details](https://i.snipboard.io/Pabk0U.jpg)
