### ISSUE TITLE
Phase 2: Components and Props Quiz, question issue 

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/phase-2-quiz-components-and-props#2]
### Canvas Link

https://learning.flatironschool.com/courses/6265/quizzes/44552?module_item_id=540226

### Concern

Question 11 has the options of False/Yes, not False/True. 

![image](https://user-images.githubusercontent.com/98498031/220723175-867c617c-de37-4e7c-8228-b1e510ef3c63.png)

**Comment by lizbur10** [comment]
Hi @SWhalley1130 ! Thanks for catching this - it has now been fixed. Note that you may not see the update in your Canvas course because students have already taken the quiz, but it will be fixed for future cohorts.

Thanks for contributing to the Flatiron School curriculum 💙
