### ISSUE TITLE
QUIZ QUESTIONS FOR COMPONENTS PHASE 2 PROBLEMS

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/phase-2-quiz-components-and-props#4]
### Canvas Link

https://learning.flatironschool.com/courses/6558/quizzes/47488

### Concern

QUESTIONS 1, 2, 3, 5 ALL HAVE INVALID SYNTAX FOR THE COMPONENTS:

function Card({title, subtitle})
{
return (
<div>
<h1>{title}h1>
<p>{subtitle}p>
div>
);
}

NOTICE THE h1 TAG IS NOT PROPERLY CLOSED. SAME FOR THE p TAG. ON THESE QUESTIONS THE EXAMPLES WERE LIKE THAT WHICH WOULD YIELD INCORRECT ANSWERS IF SOMEONE WERE TO SAY NONE OF THE OPTIONS WERE CORRECT BECAUSE THEY WOULD BE CORRECT.

THE CORRECT EXAMPLE LOOKS LIKE:

function Card({title, subtitle})
{
return (
<div>
<h1>{title}</h1>
<p>{subtitle}</p>
div>
);
}

IT MAY BE A PROBLEM WITH THE SLASH ITSELF. AS JAVASCRIPT USES THE BACKSLASH AS AN ESCAPE CARACTER.
 

### Additional Context

QUESTIONS 6 AND 11 DISPLAY CORRECTLY. The ANSWERS assuming the EXAMPLES WERE CORRECT SYNTAX WOULD HAVE BEEN CORRECT. SO ALL OF THE EXAMPLES FOR QUESTIONS 1, 2, 3, AND 5 NEED TO BE CHANGED.

### Suggested Changes

FIX ALL OF THE EXAMPLES AND/OR ANSWERS FOR QUESTIONS 1, 2, 3 AND 5.

function Card({title, subtitle})
{
return (
<div>
<h1>{title}h1>
<p>{subtitle}p>
div>
);
}

NEEDS TO BE:

function Card({title, subtitle})
{
return (
<div>
<h1>{title}</h1>
<p>{subtitle}</p>
div>
);
}

IT MAY BE A PROBLEM WITH THE SLASH ITSELF. AS JAVASCRIPT USES THE BACKSLASH (\) AS AN ESCAPE CARACTER.

**Comment by ckelly38** [comment]
The message got formatted wrong. Just treat it as plain text and ignore the formatting. I did not format it. The computer did that.

**Comment by lizbur10** [comment]
Hi @ckelly38 ! Thanks for bringing this to our attention - it has now been fixed 💙
