### ISSUE TITLE
Html closing tags broken on question 3

### ISSUE THREAD

**Issue by dader34** [learn-co-curriculum/phase-2-quiz-components-and-props#5]
### Canvas Link

https://learning.flatironschool.com/courses/6844/quizzes/51036?module_item_id=607167

### Concern

Closing html tags are broken in the multi choice question

### Additional Context

<img width="1470" alt="Screenshot 2023-10-02 at 8 39 39 PM" src="https://github.com/learn-co-curriculum/phase-2-quiz-components-and-props/assets/56900960/945be742-4ffd-4343-96be-0b2fe9ad4f25">

### Suggested Changes

Add closing tags

**Comment by lizbur10** [comment]
Hi @dader34 ! Thanks for bringing this to our attention - it has now been fixed 💙
